import Navbar from "../components/Navbar.jsx";

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-slate-950 text-white">
      <Navbar />
      <main className="max-w-3xl mx-auto px-6 py-16 prose prose-invert">
        <p className="text-cyan-400 text-sm font-medium mb-2">Legal</p>
        <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
        <p className="text-gray-500 text-sm mb-10">Last updated: August 2026</p>

        <div className="space-y-8 text-gray-300">
          <section>
            <h2 className="text-xl font-semibold text-white mb-2">1. Acceptance of terms</h2>
            <p>By creating an account or using Confid.ai ("the Service"), you agree to these Terms of Service. If you do not agree, please do not use the Service.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-2">2. Description of service</h2>
            <p>Confid.ai provides AI-powered communication practice across four modes: Interview, Presentation, Stage Speech, and Group Discussion. The Service uses your camera and microphone to provide feedback and scoring. This feedback is generated by AI and is intended for practice purposes only - it is not professional coaching, career, or psychological advice.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-2">3. Accounts</h2>
            <p>You must provide accurate information when creating an account. You are responsible for maintaining the confidentiality of your password and for all activity under your account. You must be at least 13 years old to use the Service.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-2">4. Plans and payments</h2>
            <p>New accounts receive one free trial session per practice mode (four sessions total). Continued access requires a paid plan:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>Student Plan: Rs.299 for 6 months, requires verification of a valid student ID. Access to the Student Plan is granted only after manual review and approval of the submitted ID.</li>
              <li>Regular Plan: Rs.799 for 6 months, activated immediately upon successful payment.</li>
            </ul>
            <p className="mt-2">Payments are processed via Razorpay. Plans do not auto-renew; you will need to manually resubscribe after your plan expires. All payments are currently non-refundable except where required by law.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-2">5. Student verification</h2>
            <p>If you subscribe to the Student Plan, you agree to upload a genuine, valid student identification document. Submitting false or fraudulent documents may result in immediate termination of your account without refund.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-2">6. Camera and microphone use</h2>
            <p>The Service requires access to your device's camera and microphone during practice sessions to provide AI-based feedback. Video and audio are processed for the purpose of generating your session score and are not used for any purpose beyond providing you the Service, except as described in our Privacy Policy.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-2">7. Acceptable use</h2>
            <p>You agree not to misuse the Service, attempt to access other users' data, interfere with the Service's operation, or use the Service for any unlawful purpose.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-2">8. Disclaimer of warranties</h2>
            <p>The Service is provided "as is" without warranties of any kind. AI-generated feedback and scores are approximations and may not be fully accurate. Confid.ai does not guarantee any specific outcome, such as interview success or job placement, from use of the Service.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-2">9. Limitation of liability</h2>
            <p>To the maximum extent permitted by law, Confid.ai shall not be liable for any indirect, incidental, or consequential damages arising from your use of the Service.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-2">10. Changes to these terms</h2>
            <p>We may update these Terms from time to time. Continued use of the Service after changes constitutes acceptance of the revised Terms.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-2">11. Contact</h2>
            <p>For questions about these Terms, contact us at the email associated with this account's support channel.</p>
          </section>
        </div>
      </main>
    </div>
  );
}
